# Generated by Django 3.2.18 on 2024-04-17 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MtmFirst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('mtm_first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.mtmfirst')),
            ],
        ),
        migrations.CreateModel(
            name='MtmSecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('connections_to_firsts', models.ManyToManyField(to='test.MtmFirst')),
            ],
        ),
    ]
